name: Node.js CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - name: 拉取代码
      uses: actions/checkout@v4

    - name: 设置 Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: 进入 server 目录并安装依赖
      run: |
        cd server
        npm install

    - name: 运行测试
      run: |
        cd server
        npm test